name: cozy_v2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  google_fonts: ^3.0.1
  url_launcher: ^6.1.11
  intl: ^0.18.0
  flutter_svg: ^1.1.6
  rive: ^0.12.3
  motion_toast: ^2.7.9
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/rive_assets/
    - assets/lottie_assets/

  